### ISSUE TITLE
Some kData's axis 8 is 2 which raises a conflict in the read_ocmr.py 

### ISSUE THREAD

**Issue by qianchne** [MRIOSU/OCMR#1]
For example, kData's shape of 'fs_0017_3T.h5' is (384, 165, 1, 30, 16, 1, 1, 1, 2)
In the  read_ocmr.py, it runs:
    try:
        nAverage = hdr.encoding.encodingLimits.average.maximum + 1
    except:
        nAverage = 1

 Here comes a conflict, nAverage will be 1 which is smaller than the actual avg 2.
I guess code should be modified as :
    try:
        nAverage = enc.encodingLimits.average.maximum + 1
    except:
        nAverage = 1
the conflict will be solved. It works in my trial.
Thank you for your contribution to this open CMR database.

**Comment by MRIOSU** [comment]
Yes. It is a bug in "read_ocmr.py". Thank you so much for your test. I will update "read_ocmr.py" soon.
